name: Build and Deploy
run-name: ${{ github.actor }} is running an action.

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run build script
      run: |
        python build.py

    - name: Debug build output
      run: |
        echo "::group::Build directory contents"
        ls -R build
        echo "::endgroup::"
    - name: Deploy to prod branch
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "todo-github-ci@sammyhost.uk"

        # Switch to orphan branch
        git switch --orphan prod

        # Clear everything
        git rm -rf .

        # Copy built site contents into current root
        cp -r build/. .

        # Check contents to be sure
        ls -la

        git add .
        git commit -m "Deploy built site"
        git push -f origin prod
